steps:
  - name: 'gcr.io/cloud-builders/go:alpine'
    args: ['get', 'github.com/ant0ine/go-json-rest/rest']
    env: ['PROJECT_ROOT=github.com/m-saitou/go-rest-server']
  - name: 'gcr.io/cloud-builders/go:alpine'
    args: ['install', '.']
    env: ['PROJECT_ROOT=github.com/m-saitou/go-rest-server']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-rest-server', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/go-rest-server']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'go-rest-server', '--image', 'gcr.io/$PROJECT_ID/go-rest-server', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images: ['gcr.io/$PROJECT_ID/go-rest-server']